### ISSUE TITLE
Is there any way to let hll++ cardinality increasing？

### ISSUE THREAD

**Issue by mtunique** [addthis/stream-lib#122]
Is there any way to let hll++ cardinality bigger than before offer one new value?

**Comment by abramsm** [comment]
I do not follow the question.  Can you provide an example?

**Comment by mtunique** [comment]
```java
        HyperLogLogPlus hyperLogLogPlus = new HyperLogLogPlus(16);
        for(int i = 0; i < 400000; i++) {
            long pre = hyperLogLogPlus.cardinality();
            hyperLogLogPlus.offer(i);
            long now = hyperLogLogPlus.cardinality();
            if (now < pre) {
                System.out.printf("%d %d\n", pre, now);
                hyperLogLogPlus.cardinality();
            }
        }
```

output:
```
327858 327682
```

**Comment by abramsm** [comment]
I'll look at code later but I suspect this is happening when the data
structure transitions to sparse mode.  Does it only happen once?

**Comment by mtunique** [comment]
Anytime and always these values  `327858 327682`.

**Comment by abramsm** [comment]
This is just a quirk of the probabilistic calculation.  The register sum
changes from

9454.113

to

9454.008

when you offer that additional on when i = 329514.  See line 506 of
HyperLogLogPlus to see the code i'm talking about.  If you set a breakpoint
for i=329514 you can step through and see what happens.

On a side note calling cardinality that often is very slow (not recommended
for production use case).

Matt

**Comment by mtunique** [comment]
Thanks @abramsm .

Do you have some trick methods to let cardinality bigger than before offer one new value ?

**Comment by abramsm** [comment]
I don't understand the question.  Please try to explain what you are
looking for in more detail.

**Comment by oertl** [comment]
The current implementation does not guarantee monotonicity. The cardinality estimate might become smaller after inserting a new element. The root cause is that HyperLogLog++ is switching between different cardinality estimation approaches and the transitions are not always smooth. In addition, empirical data is interpolated to correct the bias, which could also lead to the observed behavior. In order to ensure monotonicity you probably need to use a different cardinality estimation algorithm that does not rely on empirical data and that uses only a single estimation approach for the full cardinality range. I am currently working on a paper that presents such new cardinality estimation algorithms, see https://github.com/oertl/hyperloglog-sketch-estimation-paper.

**Comment by mtunique** [comment]
Thanks all @oertl @abramsm .

**Comment by abramsm** [comment]
Otmar -

That paper looks very interesting.  It will take me a while to truly digest
it.  It would be great if you can contribute an implementation of your new
algorithm to stream-lib.

Matt

**Comment by oertl** [comment]
Matt, 

I would like to, if I had more spare time. I still have to refine and finish my paper first.

Otmar
