### ISSUE TITLE
Explanation needed on StreamSummary's top-k results

### ISSUE THREAD

**Issue by mhaddadi** [addthis/stream-lib#132]
Hello,
when running this test : 
```java
StreamSummary<String> vs = new StreamSummary<String>(3);
String[] stream = { "X", "X", "Y", "Z", "A", "B", "C", "X", "X", "A", "A", "A", "1", "2", "3", "4", "5", "6" };
for (String i : stream) {
    vs.offer(i);
}
System.out.println(vs);
```
I get as result : `[{6:[{4:5},{5:5},{6:5}]}]`.

I wonder if this is normal behavior or a bug. I would suggest to reset counter.count to 0 in the method StreamSummary#offerReturnAll when a new item overrides the item with least hits.

Thanks for your analysis. Best regards.

**Comment by abramsm** [comment]
@mhaddadi This is expected behavior.  The details of the approach is described in Efficient Computation of Frequent and Top-k Elements in Data Streams (https://link.springer.com/chapter/10.1007/978-3-540-30570-5_27).

The basic idea is that you can efficently estimate the cardinality of the top n elements in a stream by using the count value of the evicted member for its replacement.  Certainly you can create abusive corner cases where this is not the case.  However in large data sets (which this data structure is designed for) the results turn out well.  In practice if you are storing the top n items in the stream summary the top n-y elements in that summary will be the *most* accurate.

**Comment by mhaddadi** [comment]
Thanks @abramsm, I get it better.
