### ISSUE TITLE
RegisterSet incorrectly allocates the space needed to track counts

### ISSUE THREAD

**Issue by hbs** [addthis/stream-lib#88]
The int array that's allocated in RegisterSet does not contain enough entries to accomodate correct counts for a given value of p.

Each count takes 6 bits, meaning that to store 2^p counts you need 6*(2^p)/8 bytes, not 2^p/6.

The counts are therefore incorrect, which can be detected by feeding for example hashes from 0 to (2^p-1) << (64 -p) in steps of 1 << (64 - p), the result should be 2**64-1 but it is 6194288074

**Comment by tea-dragon** [comment]
I believe this implementation uses 5 bits per count (See: https://github.com/addthis/stream-lib/blob/master/src/main/java/com/clearspring/analytics/stream/cardinality/RegisterSet.java#L22). This means that to store 2**p counts, you do need 5*(2**p)/8 bytes -- however, it looks like RegisterSet uses (2**p)/6 _integers_. This is equivalent to 4*(2**p)/6 bytes, meaning 5/8 bytes and 4/6 bytes per count respectively.

You will note that 4/6 is a larger amount, and is even larger than strictly needed. I believe this is due to an implementation detail where the last two bits of an integer are left wasted. However, that should not cause a correctness issue in and of itself.

Your example failing case may still be valid for a different reason though? I am having a little trouble following the context exactly.. maybe you can include a failing test case?

**Comment by hbs** [comment]
The failing test is simple, feed the estimator with 2**p synthetic hashes containing 64-p bits set to 0 and the full set of 2**p prefixes, with p < 32, the result should be Long.MAX_VALUE, but since only 5 bits are used for keeping track of the count, the cardinality is off.

**Comment by tea-dragon** [comment]
Increasing the bits per count has a non-trivial affect on memory footprint, and makes the choice between hll and hllp a little less straight forward. Additionally, I have doubts about the possibility of a real use case involving cardinalities on the order of Long.MAX_VALUE. (iirc, the original paper even says cardinalities close to that amount would require additional corrections that they didn't bother with for that reason).

However, it does seem like it would be easy enough to implement, and the hllp paper does suggest upgrading to 6 in general. It would have to be specific to hllp though (hll does not want more than 5), and ideally would not have a negative impact on existing use cases.

**Comment by abramsm** [comment]
Google did end up needing 6 bits.  I'm not aware of use cases outside of
that which required 6 bits.  Should we make it a config param?

**Comment by tea-dragon** [comment]
That is probably reasonable. We could also do a dynamic resizing if we wanted to get real fancy, but I'm not sure off hand how much of that value space is already handled by the sparse set rep.

In any event, the title/ initial post of this issue seems to no longer be representative of the continuing discussion, so maybe we should move this to a new issue called either "hllp should use six bits per register" or "better support for different register sizes" (depending on how you look at it).

**Comment by abramsm** [comment]
+1

**Comment by tea-dragon** [comment]
closed in favor of #89

lmk if this does not seem to address your concerns
